import {
  WINSTON_MODULE_NEST_PROVIDER,
  WINSTON_MODULE_OPTIONS,
  WINSTON_MODULE_PROVIDER,
} from "nest-winston";

export {
  WINSTON_MODULE_NEST_PROVIDER,
  WINSTON_MODULE_OPTIONS,
  WINSTON_MODULE_PROVIDER,
};
